spring:
  application:
    name: algoboza

  datasource:
    url: jdbc:mysql://${DB_HOST}/demo_1
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  
  
  output:
    ansi:
      enabled: always


  jpa:
    hibernate:
      ddl-auto: update  # (create, update, validate, none ? ??)
    show-sql: false       # ???? SQL ?? ?? ??
    properties:
      hibernate:
        format_sql: true # SQL? ?? ?? ??

  # Google smtp server 사용
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL} #앱 비밀번호 발급받은 google 계정
    password: ${GOOGLE_PASSWORD} #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


  # Logging Setting
  logging:
    level:
      root: INFO
    logback:
      rolling-policy:
        max-file-size: 10MB
    file:
      name: log/demo1.log

server-url: ${SERVER_URL}

jwt:
  secret: ${JWT_SECRET_KEY}

fast:
  api_key: ${FAST_API_KEY}

proxy:
  username: ${PROXY_USERNAME}
  password: ${PROXY_PASSWORD}






